# Generated by Django 3.0.4 on 2020-03-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='userdetails',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.Userdetails'),
        ),
    ]
